name: Financiero
channels:
  - defaults
dependencies:
  - _libgcc_mutex=0.1
  - _openmp_mutex=5.1
  - asttokens=2.0.5
  - backcall=0.2.0
  - ca-certificates=2023.12.12
  - comm=0.1.2
  - debugpy=1.6.7
  - decorator=5.1.1
  - exceptiongroup=1.2.0
  - executing=0.8.3
  - importlib-metadata=7.0.1
  - importlib_metadata=7.0.1
  - ipykernel=6.28.0
  - ipython=8.15.0
  - jedi=0.18.1
  - jupyter_client=8.6.0
  - jupyter_core=5.5.0
  - ld_impl_linux-64=2.38
  - libffi=3.4.4
  - libgcc-ng=11.2.0
  - libgomp=11.2.0
  - libsodium=1.0.18
  - libstdcxx-ng=11.2.0
  - matplotlib-inline=0.1.6
  - ncurses=6.4
  - nest-asyncio=1.6.0
  - openssl=3.0.13
  - parso=0.8.3
  - pexpect=4.8.0
  - pickleshare=0.7.5
  - pip=23.3.1
  - platformdirs=3.10.0
  - prompt-toolkit=3.0.43
  - psutil=5.9.0
  - ptyprocess=0.7.0
  - pure_eval=0.2.2
  - pygments=2.15.1
  - python=3.9.18
  - python-dateutil=2.8.2
  - pyzmq=25.1.2
  - readline=8.2
  - setuptools=68.2.2
  - six=1.16.0
  - sqlite=3.41.2
  - stack_data=0.2.0
  - tk=8.6.12
  - tornado=6.3.3
  - traitlets=5.7.1
  - typing_extensions=4.9.0
  - wcwidth=0.2.5
  - wheel=0.41.2
  - xz=5.4.6
  - zeromq=4.3.5
  - zipp=3.17.0
  - zlib=1.2.13
  - pip:
      - altair==5.2.0
      - appdirs==1.4.4
      - attrs==23.2.0
      - beautifulsoup4==4.12.3
      - bleach==6.1.0
      - blinker==1.7.0
      - bokeh==3.3.4
      - cachetools==5.3.3
      - certifi==2024.2.2
      - charset-normalizer==3.3.2
      - clarabel==0.7.1
      - click==8.1.7
      - colorcet==3.1.0
      - contourpy==1.2.0
      - cvxpy==1.4.2
      - cycler==0.12.1
      - cython==3.0.8
      - ecos==2.0.13
      - et-xmlfile==1.1.0
      - fonttools==4.49.0
      - frozendict==2.4.0
      - gitdb==4.0.11
      - gitpython==3.1.42
      - holoviews==1.18.3
      - html5lib==1.1
      - hvplot==0.9.2
      - idna==3.6
      - importlib-resources==6.1.2
      - joblib==1.3.2
      - jsonschema==4.21.1
      - jsonschema-specifications==2023.12.1
      - kiwisolver==1.4.5
      - linkify-it-py==2.0.3
      - lxml==5.1.0
      - markdown==3.5.2
      - markdown-it-py==3.0.0
      - markupsafe==2.1.5
      - matplotlib==3.8.3
      - mdit-py-plugins==0.4.0
      - mdurl==0.1.2
      - multitasking==0.0.11
      - numpy==1.26.2
      - openpyxl==3.1.2
      - osqp==0.6.5
      - packaging==23.2
      - pandas==2.1.4
      - pandas-datareader==0.10.0
      - panel==1.3.8
      - param==2.0.2
      - patsy==0.5.6
      - peewee==3.17.1
      - pillow==10.2.0
      - plotly==5.20.0
      - pmdarima==2.0.4
      - protobuf==4.25.3
      - pyarrow==15.0.0
      - pybind11==2.11.1
      - pydeck==0.8.1b0
      - pyparsing==3.1.1
      - pyportfolioopt==1.5.5
      - pytz==2023.3.post1
      - pyviz-comms==3.0.1
      - pyyaml==6.0.1
      - qdldl==0.1.7.post0
      - referencing==0.33.0
      - requests==2.31.0
      - rich==13.7.1
      - rpds-py==0.18.0
      - scikit-learn==1.4.1.post1
      - scipy==1.11.4
      - scs==3.2.4.post1
      - seaborn==0.13.2
      - smmap==5.0.1
      - soupsieve==2.5
      - statsmodels==0.14.1
      - streamlit==1.31.1
      - tenacity==8.2.3
      - threadpoolctl==3.3.0
      - toml==0.10.2
      - toolz==0.12.1
      - tqdm==4.66.2
      - tzdata==2023.3
      - tzlocal==5.2
      - uc-micro-py==1.0.3
      - urllib3==2.2.1
      - validators==0.22.0
      - watchdog==4.0.0
      - webencodings==0.5.1
      - xyzservices==2023.10.1
      - yfinance==0.2.37
prefix: /home/PedroSci/miniconda3/envs/Financiero
